service: import-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http: GET importProducts
