service: import-service
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-jest-plugin

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::macbook-shop-uploaded'
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::macbook-shop-uploaded/*'

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http: GET import
        request:
          parameters:
            querystrings:
              name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: macbook-shop-uploaded
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
