service: authorization-service
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  tokenAuth:
    handler: handler.basicAuthorizer
